ci: update static artifact actions to v4
dunglas/frankenphp pull request #1264
Opened 2024-12-19 08:41 UTC by vinceAmstoutz

Completes #1255

2024-12-19 19:14 UTC, withinboredom approved these changes

2024-12-19 20:46 UTC, dunglas requested changes

2024-12-19 20:46 UTC, dunglas commented on .github/workflows/static.yaml
> +          name: frankenphp-linux-${{ matrix.platform == 'linux/amd64' && 'x86_64' || 'aarch64' }}${{ matrix.debug && '-debug' || '' }}${{ matrix.mimalloc && '-mimalloc' || '' }}-${{ steps.prepare.out
This should be reverted, it's a classic upload, not a trick to pass metadata to another workflow. Also, the platform is already in the name.

2024-12-19 20:46 UTC, dunglas commented on .github/workflows/static.yaml
> +          echo "sanitized_platform=${platform//\//-}" >> "${GITHUB_OUTPUT}"
It's not necessary here, we don't use Docker for Mac builds.

2024-12-19 20:46 UTC, dunglas commented on .github/workflows/static.yaml
> +          name: frankenphp-mac-${{ matrix.platform }}-${{ steps.prepare.outputs.sanitized_platform }}
To revert, it's a classic upload.

2024-12-20 08:20 UTC, dunglas requested changes

2024-12-20 08:20 UTC, dunglas commented on .github/workflows/static.yaml
>            name: metadata-static-builder
Here we need the sanitized platform

2024-12-20 08:49 UTC, dunglas approved these changes

2024-12-20 09:56 UTC, merged

2024-12-20 09:56 UTC, dunglas commented
Thanks!