feat: thread autoscaling
dunglas/frankenphp pull request #1266
Opened 2024-12-19 15:14 UTC by Alliballibaba2

I originally wanted to just create a PR that allows adding threads via the admin API, but after letting threads scale automatically, that PR kind of didn't make sense anymore by itself.

So here is what this PR does:

It adds 4 Caddy admin endpoints

```
POST     /frankenphp/workers/restart   # restarts workers (this can also be put into a smaller PR if necessary)
GET      /frankenphp/threads           # prints the current state of all threads (for debugging/caddytests)
PUT      /frankenphp/threads           # Adds a thread at runtime - accepts 'worker' and 'count' query parameters
DELETE   /frankenphp/threads           # Removes a thread at runtime - accepts 'worker' and 'count' query parameters
```

Additionally, the PR also introduces a new directive in the config: `max_threads`.

```
frankenphp {
    max_threads 200
    num_threads 40
}
```

If it's bigger than `num_threads`, worker and regular threads will attempt to autoscale after a request on a few different conditions:
- no thread was available to immediately handle the request
- the request was stalled for more than a few ms (15ms currently)
- no other scaling is happening at that time
- A CPU probe (50ms) successfully determines that PHP threads are consuming less than a predefined amount of CPU (80% currently)
- we have not reached max_threads yet

This is all still a WIP. I'm not yet sure if `max_threads` is the best way to configure autoscaling or if it's even necessary to have the PUT/DELETE endpoints. Maybe it would also make sense to determine max_threads based on available memory.
I'll conduct some benchmarks showing that this approach performs better than default settings in a lot of different scenarios (and makes people worry less about thread configuration).

In regards to recent issues, spawning and destroying threads would also make the server more stable if we're experiencing timeouts (not sure yet how to safely destroy running threads).

2024-12-19 17:39 UTC, AlliBalliBaba commented
This PR doesn't really have 100+ commints, it was just forked from #1185. 
Also, static binary seems to be failing rn, like in #1260 and #1264

2024-12-19 17:53 UTC, dunglas commented
Static binary failure seems to be because of https://github.com/crazywhalecc/static-php-cli/issues/577

2024-12-22 00:10 UTC, AlliBalliBaba commented
I added some load test simulations. Not sure yet if I want to keep them in the repo, it sure would require fixing a lot of linting errors.
They can be run with ./testdata/performance/perf-test.sh

2024-12-22 22:39 UTC, AlliBalliBaba commented
Scaling currently works like this:
- After every request that is not immediately handled by a thread, start a timer (10ms currently)
- If the timer is triggered, start autoscaling and reset the timer with an exponential backoff
- When scaling, check that the CPU usage is not already above 80% for 40ms (and allow no other scaling)
- Every 5s, look for auto-scaled threads that have been idle for more that 5s and terminate at most 10 of them

Here are my findings from running a few load-test scenarios. I decided to just simulate load and latency via a PHP script. Doing an authentic load-test would have always involved setting up an unbiased cloud environment, which might be something for a different day. Keep in mind that the VUs were adjusted for 20 CPU cores:

### Hello world
Type | Threads | handled requests
--- | --- | --- |
Default | 40 | 1,600,000
Scaling | 8 -14 | 1,850,000
Ideal | 8 | 1,900,000

The hello world scenario tests raw server performance. It ended up being the only scenario in which a server with lower amount of threads was able to handle more requests. I guess I overestimated the impact of CPU contention in other cases

### Database simulation

Type | Threads | handled requests
--- | --- | --- |
Default | 40 | 260,000
Scaling | 10 -100 | 420,000
Ideal | 100 | 530,000

This test simulates 1-2 DB queries on 1-10ms latency with load similar to a Laravel request, probably a very common pattern for a lot of apis. What surprised me most is that in this scenario 5xCPU cores ended up being the ideal amount of threads - which is why I would probably recommend a default setting that at least scales to 5xCPU cores.

The reason why 'scaling' was able to handle less requests than 'ideal' is that it takes some time to catch up to the ideal. The overhead of scaling itself is actually relatively negligible and doesn't even appear in the flamegraphs.

### External API simulation

Type | Threads | handled requests
--- | --- | --- |
Default | 40 | 23,500
Scaling | 10 -600 | 160,000
Ideal | 600+? | 190,000

This test leans more into big latencies. A lot of applications access external apis or microservices that have much higher response times than databases (test ran with 10ms-150ms). The main learning here is that if you know latencies to be this high, it might not be unreasonable to spawn 30xCPU cores. Threads are in general more lightweight than FPM processes, how many workers could reasonably run on 1GB of RAM is something I haven't tested yet though.

### Computation heavy
Type | Threads | handled requests
--- | --- | --- |
Default | 40 | 108,000
Scaling | 10-27 | 106,000
Ideal | 25 | 109,000

This test goes into the other extreme and does almost no IO. Main learning here is: If the server is not IO bound, then anything above 20 CPU cores behaves pretty similar. In this case Scaling did not go over 27 threads due to high CPU usage. This is the only test where checking for CPU usage was beneficial since we save memory by not spawning more threads.

### Hanging server
Type | Threads | handled requests
--- | --- | --- |
Default | 40 | 9,300
Scaling | 10-200 | 34,000
Ideal | 200 | 32,000

This test introduces a 2% chance for a 'hanging' request that takes 15s to complete. I chose this ratio on purpose since it will already make the server hang completely in default settings sometimes. Interestingly, scaling performed better here than spawning a fixed high amount of threads. In some situations being able to spawn 'fresh' threads seems to be beneficial.

### Timeouts
Type | Threads | handled requests
--- | --- | --- |
Default | 40 | 12,400
Scaling | 10-200 | 90,000
Ideal | 200 | 100,000

This is another resilience simulation. An external resources becomes unavailable every other 10s and causes timeouts for all requests. Again, a server with a higher amount of threads performs much better in this situation and can recover faster. On very severe hanging it might also make sense to terminate and respawn threads (something for a future PR).

2024-12-23 10:38 UTC, withinboredom commented
@AlliBalliBaba I spot some performance improvements that can be made (I think -- needs some testing), but trying to explain it in a review would probably take too long of back-and-forth. Is this branch stable enough to just open a PR to your PR?

2024-12-23 23:25 UTC, dunglas commented on caddy/admin_test.go
> +		panic(err)
`assert.NoError()`?

2024-12-23 23:25 UTC, dunglas commented on caddy/admin_test.go
> +	} else {
Nit: could be an early return instead.

2024-12-23 23:25 UTC, dunglas commented on caddy/admin_test.go
> +	if err != nil {
Could be `NoError`

2024-12-23 23:25 UTC, dunglas commented on caddy/admin_test.go
> +	if err != nil {
Same

2024-12-23 23:25 UTC, dunglas commented on caddy/caddy.go
> +				v, err := strconv.Atoi(d.Val())
Maybe should we use `ParseUint()` to prevent negative values?
The "problem" already exists with `NumThreads`.

2024-12-23 23:25 UTC, dunglas commented on docs/worker.md
> +### Restart Workers manually
```suggestion
### Restart Workers Manually
```

2024-12-29 17:42 UTC, AlliBalliBaba commented on caddy/admin.go
> +	if !r.URL.Query().Has("worker") {
The reason I'm explicitly checking for 'has' here is so something like this also works:
`curl -X PUT http://localhost:2019/frankenphp/threads?worker`

2024-12-29 23:04 UTC, AlliBalliBaba commented
Following the discussion in #1289 I added another configuration called 'scaling'. Currently it's just 'on' and 'off'.
```
frankenphp {
	num_threads 40
	max_threads 200
	scaling off
}
```

@withinboredom I noticed that your scaling strategy would potentially spawn an unlimited amount of goroutines waiting for the scaling lock, so i reverted it back to my strategy for now. If necessary we can add different scaling strategies by implementing the `scalingStrategy` interface.

I don't know yet how much I like having the scaling strategy as a configuration, but it should at least be possible to turn scaling off somehow I guess.

2025-01-09 11:57 UTC, AlliBalliBaba commented
After some more consideration, these are probably the scaling strategies I'll initially implement:

`scaling off `                    - no scaling if explicitly set or max_threads not defined
motivation:
- allow users to set max_threads, but disable autoscaling and just scale threads manually via admin api

`scaling safe (default)`     - only scales if requests are being stalled for a long time and never fully stops threads
motiviations:
- scale slowly to keep threads 'in reserve' for situations where some external resource might cause the server to hang
- prevent incompatibilities from leaky extensions like in #1296

`scaling eager`               - start and stop threads agressively (@withinboredom's implementation)
motiviations:
- adapt quickly to request spikes

2025-01-09 15:09 UTC, dunglas commented
Couldn't we start with a single strategy? Users will struggle to find which strategy to use, and if at some point we manage to entirely get read of threads to use goroutines (there is ongoing work from the PHP Foundation to make PHP signal-free, that would allow using goroutines directly).

In general, I like the Go philosophy of "no knob" unless strictly necessary.

2025-01-09 15:22 UTC, Toflar commented
> In general, I like the Go philosophy of "no knob" unless strictly necessary.

I totally agree. I would also argue that this applies to the config values regarding`num_threads` and `max_threads` as well. Only a selected number of devs will know how to tune this but the vast majority won't.
What people are able to do is to configure max resources (CPU, memory) because that's what they can manage and understand. 
Imho good DX/UX would be if frankenphp just tried to optimize according to the max resources configured and picked the right number of threads itself. Sorry to chip in here - I have no clue if this is even doable 😊

2025-01-09 16:25 UTC, AlliBalliBaba commented
Hmm I guess I agree as well. In that case I'd prefer to scale conservatively. Maybe it's possible to automatically calculate the number of possible threads via PHP's configured memory limit? Would we just start at `num_threads` and scale to that limit?

As a sidenote: even if we do get rid of threads there still needs to be some amount of underlying PHP worker instances. The only time where a constant amount of workers always makes sense is if PHP and its frameworks are fully async and non-blocking.

2025-01-09 20:43 UTC, withinboredom commented
While Go doesn't have many knobs, it does have knobs through environment variables because it's impossible to be smart enough to program something to be 1000% generic. Sane defaults that work in the vast majority of cases is good. But if you are looking for a use-case, we have an api that receives anywhere between a few api requests a second to hundreds per second, to a few requests per minute. Scaling conservatively isn't going to be fast enough to be useful.

I think having the feature and having it documented is valuable, along with sane defaults that work in the vast majority of cases.

That being said, many people overprovision servers because 99% of requests use <50% of the allocated resources, but occasionally you need to generate a report or do some heavy processing, so the limits are set high enough for those requests. Determining a max_threads based on memory is probably not good enough, but probably a good default for someone just getting started.

2025-01-09 23:06 UTC, dunglas commented
I agree with that too. My point is to try to have the best defaults, and to try to not "bloat" the project by only adding the few strategies as possible, and only if they are justified by real-life use cases.

2025-01-10 10:52 UTC, AlliBalliBaba commented
I think this also needs some testing on real world applications. This would be my initial plan:

- If no `max_threads` are configured, we just keep everything as-is
- If `max_threads` are defined, scale up to that limit (conservatively)
- If `maxthreads` = 'auto' calculate the limit automatically via 'memory_limit' from the php.ini

We can later change it so 'auto' is the default or add other scaling implementations if this one turns out to be too ineffective in some scenarios.

In order to properly test the `maxthreads auto` implementation I'll probably have to add a `php_ini` directive to the Caddyfile (I think this was on the Todo List)

I agree with @withinboredom that PHP's memory_limit tends to be set way too highly for most requests, especially in applications that sometimes do memory intensive stuff like converting images. So doing this might be ineffiecient memory wise:

`maxThreads = availableProcessMemory / phpMemoryLimitPerThread`

It's the only 100% 'memory safe' version, but I think we could get away with doubling this value (the current default of `num_threads` also ignores any memory limits)

2025-01-12 15:38 UTC, AlliBalliBaba commented
I added another new Caddy directive: `php_ini`

I have previously searched for ways to configure PHP in integration tests and think this is the right approach for it. Overwriting php.ini defaults via Caddyfile is generally a useful feature though, we can also document it if you are fine with the current API:

```
frankenphp {
	num_threads 20
	max_threads auto

	php_ini max_execution_time 10
	php_ini memory_limit 100M
}
```

2025-01-15 22:14 UTC, AlliBalliBaba commented
Not yet sure if we should keep the admin endpoints to add and remove threads. While the are nice to have, I'm not sure how useful they actually are. Maybe they would make sense if we allow going above max_threads? That would require locking the phpThreads slice though.

2025-01-15 23:51 UTC, dunglas commented
For the sake of simplicity, I would be to remove these endpoints for now, as long as we haven't a real-life you case for them.

WDYT?

2025-01-16 00:26 UTC, dunglas commented on caddy/caddy_test.go
> -	frankenphp_total_threads ` + cpus + `
We should keep this test isn't it?

2025-01-16 00:26 UTC, dunglas commented on caddy/watcher_test.go
>  			php
Same here?

2025-01-16 00:26 UTC, dunglas commented on docs/config.md
> +		php_ini <key> <value> # Overrides a single PHP configuration. Can be specified more than once for multiple overrides.
```suggestion
		php_ini <key> <value> # Set a php.ini directive. Can be used several times to set multiple directives.
```

2025-01-16 00:26 UTC, dunglas commented on docs/config.md
> +		max_threads <num_threads> # Limits the number of additional PHP threads that can be started at runtime. Default: num_threads.
Add docs for `auto`?

2025-01-16 00:26 UTC, dunglas commented on docs/config.md
> +You can also overwrite single configurations using the `php_ini` directive in the `Caddyfile`:
```suggestion
You can also change the PHP configuration using the `php_ini` directive in the `Caddyfile`:
```

2025-01-16 00:26 UTC, dunglas commented on frankenphp.c
> +      content_type, (char *)SG(request_info).content_type, true,
Why this change?

2025-01-16 00:26 UTC, dunglas commented on internal/cpu/cpu_fallback.go
> +
What's the purpose of this directive?

2025-01-16 00:26 UTC, dunglas commented on internal/cpu/cpu_unix.go
> +var cpuCount = runtime.NumCPU()
As we use https://github.com/uber-go/automaxprocs, maybe should we use https://pkg.go.dev/runtime#GOMAXPROCS instead?

2025-01-16 00:26 UTC, dunglas commented on internal/cpu/cpu_unix.go
> +	C.clock_gettime(C.CLOCK_MONOTONIC, &start)
We may not need C here, using `time` should be do the trick: https://pkg.go.dev/time#hdr-Monotonic_Clocks

2025-01-16 00:26 UTC, dunglas commented on phpmainthread.go
> +	// convert the php.ini overrides from the Caddy config to a C string
```suggestion
	// convert the php.ini overrides from map to a C string
```

nit: the library should be independent of Caddy

2025-01-16 09:12 UTC, AlliBalliBaba commented on caddy/caddy_test.go
> -	frankenphp_total_threads ` + cpus + `
Oh I was under the impression `MaxThreads` was introduced by #1289, I'll put the test back in

2025-01-16 09:14 UTC, AlliBalliBaba commented on frankenphp.c
> +      content_type, (char *)SG(request_info).content_type, true,
The Fuzzing tests are actually also currently failing on main, this fixes it.
I'm not sure why this suddenly started happening with PHP8.4, but `CONTENT_TYPE` should be present in `$_SERVER` regardless of whether it exists in the request header.

2025-01-16 09:18 UTC, AlliBalliBaba commented on internal/cpu/cpu_fallback.go
> +
If you mean `// -build unix`, I'm actually not sure if this does anything in newer go versions, I'll remove it.
If you mean unix in general, it's to keep it compatible with potential windows support (didn't want to break #1286)

2025-01-16 09:32 UTC, AlliBalliBaba commented on caddy/watcher_test.go
>  			php
I wanted to rename the PHP file since all it does is counting requests and it's also used in the new 'restart workers from admin api' test.

2025-01-16 11:40 UTC, AlliBalliBaba commented on internal/cpu/cpu_unix.go
> +var cpuCount = runtime.NumCPU()
This now uses time for the monotonic clock, but still C for the process clock.

2025-01-16 11:41 UTC, AlliBalliBaba commented on docs/config.md
> +		max_threads <num_threads> # Limits the number of additional PHP threads that can be started at runtime. Default: num_threads.
I added a mention, it's explained in `performance.md` for now. We can make it the default in the future if this turns out to work well.

2025-01-16 11:42 UTC, AlliBalliBaba commented on internal/cpu/cpu_unix.go
> +	C.clock_gettime(C.CLOCK_MONOTONIC, &start)
This now uses time for the monotonic clock, but still C for the process clock.

2025-01-16 11:45 UTC, AlliBalliBaba commented
I removed the POST and DELETE admin endpoints for now, we can add them back in if needed.

2025-01-27 22:07 UTC, dunglas commented
Is this one ready for prime time?

2025-01-27 23:00 UTC, AlliBalliBaba commented
Yes, I think this one should be good to go for an initial implementation via the `max_threads` configuration.
I set the channel used for scaling to nil in case scaling is inactive, so there shouldn't be any difference in behavior if `max_threads` is not set.

I might create a separate project with integration tests and some extensions/framework at some point so there's more confidence before releases.

2025-01-29 19:06 UTC, withinboredom commented
![giphy](https://github.com/user-attachments/assets/6083c625-daff-47a7-9682-a578aafb8b22)

2025-01-30 21:02 UTC, AlliBalliBaba commented
I created a small testing [repo](https://github.com/AlliBalliBaba/frankenphp-integration-tests) with Laravel, since it's the PHP Framework I'm most familiar with. Right now it just tests a few of the most popular extensions in `zts-bookworm`, but I'll probably add more if there are any problematic ones.

The only issue I found so far is that calling `opcache_reset` can lead to a crash under high load (also on main). Not sure if this only affects ZTS, but there exist simliar [issues](https://github.com/php/php-src/issues/14471) for FPM.

On worker restarts all threads are first stopped, which prevents the crashing. It's just problematic if `opcache_reset` is called directly , so maybe documenting this might be enough for now.

2025-02-02 23:48 UTC, AlliBalliBaba commented
Alright I think this is ready to merge. Not sure why watcher installation is failing right now in asan and msan

2025-02-04 22:57 UTC, AlliBalliBaba commented
@dunglas I'll merge this branch if that's ok.

It looks like the newest [watcher](https://github.com/e-dant/watcher) version needs `CLANG20` and `CLANGXX20` (`ubuntu-latest` in the pipeline has CLANG18, but it's not a problem with GCC). I fixed the used watcher version to `0.13.2` for msan and asan for now.

Also, not sure what's up with the sudden false positives in the [markdown linter](https://github.com/dunglas/frankenphp/actions/runs/13146300562/job/36685074527?pr=1266).

2025-02-04 23:56 UTC, furan917 commented
@AlliBalliBaba Feel free to tell me I am wrong as I am just passing by and skim reading.

But isn't the linter fail a true fail with a hint of misconfig, ithe GHA is linting `main` and picking up the RU docs are missing their EOLs, right?

2025-02-05 08:08 UTC, AlliBalliBaba commented
@furan917 Oh you are right, I didn't realize it was in the russian docs

2025-02-05 17:04 UTC, dunglas requested changes
Great work!! I made a bunch of comments, but this looks very close to be mergeable to me.

2025-02-05 17:04 UTC, dunglas commented on testdata/performance/perf-test.md
> +in the background. Additionally, it will run the grafana/k6 container and you'll be able to choose
```suggestion
in the background. Additionally, it will run the `grafana/k6` container and you'll be able to choose
```

2025-02-05 17:04 UTC, dunglas commented on testdata/performance/perf-test.md
> +the load test you want to run. A flamegraph.svg will be created in the `testdata/performance` directory.
```suggestion
the load test you want to run. A `flamegraph.svg` will be created in the `testdata/performance` directory.
```

2025-02-05 17:04 UTC, dunglas commented on thread-inactive.go
```suggestion
threadinactive.go
```

IIRC it's not common in go to use dashes in filenames.

2025-02-05 17:04 UTC, dunglas commented on thread-regular.go
>  package frankenphp
threadregular.go

2025-02-05 17:04 UTC, dunglas commented on thread-worker.go
>  		setupWorkerScript(handler, handler.worker)
threadworker.go

2025-02-05 17:04 UTC, dunglas commented on caddy/caddy.go
> +					f.MaxThreads = -1
Maybe should we use `0` as marker value? a maxThreads at 0 likely makes no sense, so we can use this value for "auto", and this will allow using an uint.

2025-02-05 17:40 UTC, AlliBalliBaba commented on caddy/caddy.go
> +					f.MaxThreads = -1
0 is the default and makes `max_threads` fall back to `num_threads`

2025-02-05 17:42 UTC, AlliBalliBaba commented on dev.Dockerfile
> +    ldconfig
Not sure, but without it I have to type `ldconfig` everytime after starting the dev.Docker

2025-02-05 17:42 UTC, AlliBalliBaba commented on caddy/caddy.go
> +			case "max_threads":
Sure we can, should it error in that case or just warn?

2025-02-05 20:32 UTC, AlliBalliBaba commented on caddy/admin.go
> +package caddy
Do you mean via comment or is there a specific way to mark an admin API endpoint as experimental?

2025-02-05 20:40 UTC, AlliBalliBaba commented on phpmainthread.go
> +	phpThreads = make([]*phpThread, mainThread.maxThreads)
The case where it's smaller than 0 gets handled in `setAutomaticMaxThreads()`. The main thread has to start first so we known the php.ini memory setting

2025-02-05 21:04 UTC, dunglas commented on caddy/admin.go
> +package caddy
Just a comment. The usual convention is to add `EXPERIMENTAL: ` at the beginning of the the comment block

2025-02-05 21:05 UTC, dunglas commented on caddy/caddy.go
> +			case "max_threads":
Error IMO

2025-02-05 21:05 UTC, dunglas commented on phpmainthread.go
> +	phpThreads = make([]*phpThread, mainThread.maxThreads)
0 could be an issue too, right?

2025-02-05 21:28 UTC, AlliBalliBaba commented on phpthread.go
> +		logger.Error("thread is not in reserved state", zap.Int("threadIndex", thread.threadIndex), zap.Int("state", int(thread.state.get())))
I'll adjust it a bit so we can panic here 👍

2025-02-05 21:37 UTC, AlliBalliBaba commented on scaling.go
> +// TODO: these constants need some real-world trial
Alright I'll remove the TODO 😄 , it's probably to wage

2025-02-05 21:38 UTC, AlliBalliBaba commented on scaling.go
> +	logger.Debug("shutting down autoscaling", zap.Int("autoScaledThreads", len(autoScaledThreads)))
not sure if it's worth doing Check here (sub ms performance doesn't matter on shutdown).
I can add it for consistency if you want.

2025-02-05 21:47 UTC, AlliBalliBaba commented on scaling.go
> +		// Reactivate this if there is a better solution or workaround
I don't think this needs an option right now, it would just safe some memory. 

Fixing extensions is more in the scope of a bigger PR, that also allows killing hanging/leaking threads in general.

2025-02-05 21:54 UTC, AlliBalliBaba commented on internal/cpu/cpu_fallback.go
> +//go:build !unix
Are there any others than `unix` and `windows` that we support (or plan to)? Then naming them `unix` and `windows` is fine.

2025-02-05 22:02 UTC, AlliBalliBaba commented on caddy/caddy.go
> +			case "max_threads":
this will error now if max_threads < num_threads

2025-02-05 22:03 UTC, AlliBalliBaba commented on caddy/admin.go
> +package caddy
I added a comment above Routes()

2025-02-05 22:07 UTC, AlliBalliBaba commented on phpmainthread.go
> +func ThreadDebugStatus() string {
Hmm yeah we can turn this into proper json. It's just there for testing right now

2025-02-06 09:12 UTC, AlliBalliBaba commented on caddy/caddy.go
> +	PhpIni map[string]string `json:"php_ini,omitempty"`
Maybe it would also make sense to support this format for ini configuration?

```
php_ini {
  <key> <value>
  <key=value>
}
```

2025-02-06 09:31 UTC, AlliBalliBaba commented on phpmainthread.go
> +func ThreadDebugStatus() string {
This is now a struct+json, I moved it into it's own file

2025-02-07 18:20 UTC, AlliBalliBaba commented
Alright, the debug state is now a struct and the endpoint is marked as 'experimental' and returns a JSON. Additionally, I added support for a nested php.ini configuration like this, since I think it's a very convenient feature
```
php_ini opcache.jit tracing

# or

php_ini {
	mysqlnd.collect_statistics Off
	opcache.jit tracing
}
```

2025-02-16 17:02 UTC, AlliBalliBaba commented
I removed the request path from the debugState again, it's probably not worth locking the request just for this use case.

@dunglas we can merge whenever you're ready.

2025-02-18 09:33 UTC, dunglas approved these changes

2025-02-18 11:23 UTC, AlliBalliBaba commented on worker.go
> +			metrics.StopWorkerRequest(worker.fileName, time.Since(fc.startedAt))
Nothing really since in this case the executed script and the worker script are the same

2025-02-18 21:02 UTC, AlliBalliBaba commented
We can wait for #1388 if you want to have a fully stable version before scaling is introduced.

2025-02-19 19:39 UTC, merged

2025-03-12 22:58 UTC, jsamouh commented
Any chance to have a new version with that ? or too  soon ?