fix: check command go and xcaddy in build-static.sh
dunglas/frankenphp pull request #1298
Opened 2024-12-31 18:28 UTC by ddevsr

Checking command `go`:
```bash
+ type go
+ echo 'The "go" command must be installed. We strongly recommended installed Homebrew for automatically install Golang'
The "go" command must be installed. We strongly recommended installed Homebrew for automatically install Golang
+ exit 1
```
Checking command `xcaddy`:
```bash
+ type xcaddy
+ echo 'Something went wrong after running "go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest".'
Something went wrong after running "go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest".
++ go env GOPATH
+ PATH_USER_DOWNLOAD_GO=/root/go/bin
+ '[' -z /root/go/bin ']'
+ echo 'Your user-downloads package in Go = /root/go/bin'
Your user-downloads package in Go = /root/go/bin
```

2024-12-31 20:54 UTC, dunglas commented on build-static.sh
> +if ! type "xcaddy" >/dev/null 2>&1; then
Couldn't we just use the absolute path to `xcaddy` as we can guess it?

2025-01-01 02:44 UTC, ddevsr commented on build-static.sh
> +if ! type "xcaddy" >/dev/null 2>&1; then
Done

2025-01-01 09:17 UTC, dunglas requested changes

2025-01-01 09:17 UTC, dunglas commented on build-static.sh
> +XCADDY_COMMAND="$(go env GOPATH)/bin/xcaddy"
We should check if `xcaddy` is already in the path, and only if it isn't install it using `go install` and use the absolute path.
This would allow users to use existing local installations (for instance, when using the Debian packages provided by Caddy, or custom versions with ad hoc patches).

2025-01-01 09:17 UTC, dunglas commented on build-static.sh
> +	echo "The \"go\" command must be installed. We strongly recommended installed Homebrew for automatically install Golang"
```suggestion
	echo "The \"go\" command must be installed."
```

Not really on Linux. Any Go installation is fine as long as it is recent enough. For instance we use the Docker version by default.

2025-01-08 10:37 UTC, merged

2025-01-08 10:37 UTC, dunglas commented
Thank you!