Load custom Caddyfile from embedded app if it exists
dunglas/frankenphp pull request #494
Opened 2024-01-21 07:40 UTC by pierredup

Use the embedded `Caddyfile` if the embedded app contains a `Caddyfile` at the root

Fixes #413

2024-01-21 17:11 UTC, dunglas requested changes
Nice improvement!

I left some minor comments.

2024-01-21 17:11 UTC, dunglas commented on caddy/php-server.go
> +			}
```suggestion
			if err = caddy.Load(config, true); err != nil {
				return caddy.ExitCodeFailedStartup, err
			}
```

2024-01-21 17:11 UTC, dunglas commented on caddy/php-server.go
> +			return caddy.ExitCodeSuccess, nil
```suggestion
```

(This line cannot be reached, isnt' it?)

2024-01-22 12:31 UTC, merged

2024-01-22 12:31 UTC, dunglas commented
Thank you!

2024-03-10 22:19 UTC, sneycampos commented
Could you guys provide a simple explanation how it works? i'm using  the latest builder to add caddy-exec module, created a Caddyfile in my application root folder (/app/Caddyfile) but doesn't see to work

This is my code:

Dockerfile:
```Dockerfile
FROM dunglas/frankenphp:latest-builder AS builder

# Copy xcaddy in the builder image
COPY --from=caddy:builder /usr/bin/xcaddy /usr/bin/xcaddy

# CGO must be enabled to build FrankenPHP
ENV CGO_ENABLED=1 XCADDY_SETCAP=1 XCADDY_GO_BUILD_FLAGS="-ldflags '-w -s'"
RUN xcaddy build \
	--output /usr/local/bin/frankenphp \
	--with github.com/dunglas/frankenphp=./ \
	--with github.com/dunglas/frankenphp/caddy=./caddy/ \
    --with github.com/dunglas/caddy-cbrotli \
    --with github.com/dunglas/mercure/caddy \
    --with github.com/dunglas/vulcain/caddy \
    --with github.com/abiosoft/caddy-exec

FROM dunglas/frankenphp AS runner

ENV SERVER_NAME=:80

COPY . /app
WORKDIR /app

# Replace the official binary by the one contained your custom modules
COPY --from=builder /usr/local/bin/frankenphp /usr/local/bin/frankenphp
```

Caddyfile
```
{
    exec php /app/artisan optimize
    exec php /app/artisan about
}
```

Logs:
```log
php-1  | {"level":"info","ts":1710106973.2761014,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
php-1  | {"level":"warn","ts":1710106973.276807,"msg":"Caddyfile input is not formatted; run 'caddy fmt --overwrite' to fix inconsistencies","adapter":"caddyfile","file":"/etc/caddy/Caddyfile","line":16}
php-1  | {"level":"info","ts":1710106973.2775857,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
php-1  | {"level":"warn","ts":1710106973.277728,"logger":"http.auto_https","msg":"server is listening only on the HTTP port, so no automatic HTTPS will be applied to this server","server_name":"srv0","http_port":80}
php-1  | {"level":"info","ts":1710106973.2778854,"msg":"FrankenPHP started 🐘","php_version":"8.3.3"}
php-1  | {"level":"info","ts":1710106973.2780004,"logger":"http.log","msg":"server running","name":"srv0","protocols":["h1","h2","h3"]}
php-1  | {"level":"info","ts":1710106973.2781467,"msg":"autosaved config (load with --resume flag)","file":"/config/caddy/autosave.json"}
php-1  | {"level":"info","ts":1710106973.2781534,"msg":"serving initial configuration"}
php-1  | {"level":"info","ts":1710106973.2782197,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0x4000333580"}
php-1  | {"level":"info","ts":1710106973.278656,"logger":"tls","msg":"cleaning storage unit","storage":"FileStorage:/data/caddy"}
php-1  | {"level":"info","ts":1710106973.278754,"logger":"tls","msg":"finished cleaning storage units"}
```

Should my Caddyfile be same as default and may i change adding these module commands?