adding cbroti requirement for custom caddy build.
dunglas/frankenphp pull request #626
Opened 2024-03-04 06:33 UTC by StephenMiracle

It was failing to build and run correctly without this module. The caddyfile shows the br encoding.

2024-03-04 07:01 UTC, dunglas requested changes

2024-03-04 07:01 UTC, dunglas commented on docs/docker.md
> +- daily at 4am UTC, if new versions of the official PHP images are available
Can you revert these changes please?

2024-03-04 07:02 UTC, dunglas commented
Good catch. We need to use Go build directives to not have a hard dependency on cbrotli. I'll do that but let's update the docs in the meantime.

2024-03-04 21:36 UTC, dunglas approved these changes

2024-03-04 21:36 UTC, merged

2024-03-04 21:36 UTC, dunglas commented
Thanks!

2024-03-05 16:53 UTC, StephenMiracle commented
Ah. Thanks for updating back the asterisks. I just went to change. VS Code autoformatter. Thanks.