[WIP] add directive for frankenphp
dunglas/frankenphp pull request #92
Opened 2022-11-08 09:50 UTC by flug

2022-11-08 17:05 UTC, dunglas commented on caddy/caddy.go
> +					frankenphpTransport.Env = make(map[string]string)
You could probably initialize the map outside of the loop to simplify the code and remove this `if`.

2022-11-10 00:00 UTC, dunglas commented on caddy/caddy.go
> +		Routes: append(routes),
```suggestion
		Routes: routes,
```

?

2022-11-10 00:00 UTC, dunglas commented on caddy/caddy.go
> +	frankenphpTransport := FrankenPHPModule{}
```suggestion
	frankenphp := FrankenPHPModule{}
```

2022-11-10 13:07 UTC, dunglas commented on testdata/Caddyfile
> +	}
So the following lines can be removed, right?

Also, the indentation doesn't look good (you should be able to fix this automatically with [`caddy fmt`](https://caddyserver.com/docs/command-line#caddy-fmt).

2023-01-02 16:36 UTC, flug commented
last error : ```Error: adapting config using caddyfile: directive 'frankenphp' is not an ordered HTTP handler, so it cannot be used here```

2023-01-09 22:13 UTC, dunglas requested changes

2023-01-09 22:13 UTC, dunglas commented on caddy/caddy.go
>  	SplitPath          []string          `json:"split_path,omitempty"`
Shouldn't it be `Split` for consistency with the `php_fastcgi` directive?

2023-01-09 22:13 UTC, dunglas commented on caddy/frankenphp/Caddyfile
> +    frankenphp index {
indentation to fix.

Shouldn't be this directive outside of the global block (as `php_fastcgi`)?

Also, why do we need to pass the `index` matcher? It doesn't look defined.

Also, by default just having `frankenphp` should be enough as for `php_fastcgi`.

2023-01-09 22:13 UTC, dunglas commented on testdata/Caddyfile
> +
```suggestion
```

2023-04-24 08:43 UTC, closed without merging